/**
 * Pre-computed demo credential for testnet.
 *
 * Generated by: cd scripts && bun run src/seed-credential-tree.ts
 *
 * Params: userSecret=12345, kycLevel=1, expiryEpoch=99999999, issuerId=42, merkleIndex=0
 * Merkle root matches on-chain credential root (timelock pending).
 */

import type { Credential } from "./types";
import credentialJson from "./demoCredential.json";

export const DEMO_CREDENTIAL: Credential = {
  leaf: BigInt(credentialJson.leaf),
  kycLevel: credentialJson.kycLevel,
  expiry: credentialJson.expiry,
  issuerId: credentialJson.issuerId,
  merkleProof: credentialJson.merkleProof.map((hex) => BigInt(hex)),
  merkleIndex: credentialJson.merkleIndex,
};
